title: Alex Springer
description: AI Commerce, Content Attribution, Transparency Standards
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

linkedin_url: https://www.linkedin.com/in/jalexspringer/
github_profile_url: https://github.com/jalexspringer
email: alex@openattribution.org
